fails:StringIO#close raises an IOError when self was already closed
