fails:Executing return from within a block raises a LocalJumpError
fails:Executing return from within a block causes the method calling the method that yields to the block to return
