fails:Timeout.timeout raises Timeout::Error when it times out
