The retry statement should raise LocalJumpError if used outside of a block
