fails:IO#popen with block does not raise error when io closed inside the block
